name: lint

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'develop'

  schedule:
    - cron: '15 18 * * *'

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v2.0.3

  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: '*.md'
          config_file: .markdownlint.json
